cli+server: CHANGE: building HTML man pages
Since HTML man pages are pregenerated in GIT repository, they can
be installed even if the roff2html is not present. Till now, if
the roff2html was not present, HTML format of man pages was not
installed event they were present.

diff --git a/cli/Makefile.in b/cli/Makefile.in
--- a/cli/Makefile.in
+++ b/cli/Makefile.in
@@ -82,9 +82,7 @@ HDRS = 	commands.h \
 OBJS = $(SRCS:%.c=$(OBJDIR)/%.o)
 
 MANPAGES = doc/netopeer-cli.1
-ifneq "@ROFF2HTML@" "no"
 MANHTMLS = $(MANPAGES:%=%.html)
-endif
 
 MANPATH=$(DESTDIR)$(mandir)/man$(subst .,,$(suffix $(1)))
 define MANINSTALL
@@ -109,6 +107,10 @@ $(OBJDIR)/%.o: %.c
 	$(CC) $(CFLAGS) $(INCLUDES) $(CPPFLAGS) -fPIC -c $< -o $@
 
 %.1.html: %.1
+	@if [ -z "@ROFF2HTML@" ]; then \
+		echo "Missing roff2html"; \
+		exit 1; \
+	fi
 	@ROFF2HTML@ $< > $@
 
 .PHONY: doc
diff --git a/server/Makefile.in b/server/Makefile.in
--- a/server/Makefile.in
+++ b/server/Makefile.in
@@ -130,9 +130,7 @@ MANPAGES = manager/netopeer-manager.1 \
 	netopeer-agent.1 \
 	configurator/netopeer-configurator.1
 
-ifneq "@ROFF2HTML@" "no"
 MANHTMLS = $(MANPAGES:%=%.html)
-endif
 
 MANPATH=$(DESTDIR)$(mandir)/man$(subst .,,$(suffix $(1)))
 define MANINSTALL
@@ -159,9 +157,17 @@ $(SERVER_MODULES_CONF): $(SERVER_MODULES_CONF:%=%.tmp)
 	$(call EXPAND,$(@:%=%.tmp),$@)
 
 %.1.html: %.1
+	@if [ -z "@ROFF2HTML@" ]; then \
+		echo "Missing roff2html"; \
+		exit 1; \
+	fi
 	@ROFF2HTML@ $< > $@
 
 %.8.html: %.8
+	@if [ -z "@ROFF2HTML@" ]; then \
+		echo "Missing roff2html"; \
+		exit 1; \
+	fi
 	@ROFF2HTML@ $< > $@
 
 $(SERVER): $(SERVER_OBJS) $(SERVER_MODULES_CONF)
